apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-apps-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-apps
  template:
    metadata:
      labels:
        app: main-apps
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      containers:
        - name: main-app-generator
          image: riverfire/dwk-main-app:v0.2
          volumeMounts:
            - name: shared-volume
              mountPath: /files
        - name: main-app-reader
          image: riverfire/dwk-main-app-reader:v0.1
          volumeMounts:
            - name: shared-volume
              mountPath: /files
