apiVersion: v1
kind: Service
metadata:
  name: pingpong-app
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
    - name: pingpong-app
      port: 3000
      protocol: TCP
      targetPort: 3000
